# Generated by Django 4.0.4 on 2022-05-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stud',
            fields=[
                ('sid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('sadds', models.CharField(max_length=100)),
                ('scity', models.CharField(max_length=100)),
                ('semail', models.CharField(max_length=100)),
                ('sphon', models.IntegerField()),
            ],
        ),
    ]
