# Generated by Django 3.2.8 on 2022-05-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDApp', '0003_stud_sid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud',
            name='id',
        ),
        migrations.AlterField(
            model_name='stud',
            name='sid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
