# Generated by Django 4.0.4 on 2022-05-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('mark1', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mark2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mark3', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_mark', models.DecimalField(decimal_places=2, max_digits=6)),
                ('avg_mark', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
